### PR TITLE
Label the compare in List.sort_uniq calls

### PR DESCRIPTION
**Pull request by rleonid**
Now it builds on `4.03`

### CODE REVIEW

**Comment by agarwal** [comment]
Sorry, just saw this... GitHub is frequently not sending me notifications. Explicitly doing an @agarwal mention usually solves that problem.

I'm hesitant to merge this because it will break a merge with v0.0.3-dev. If you actually need this imminently, I could create a separate branch for it (but that's no different than having your own fork). Or just hold a bit; finishing up the new work is still a high priority for me, so the new branch should become usable soon.

**Comment by rleonid** [comment]
Not urgent and not even necessary at the moment. I figured this might be useful for tracking things down when getting a 4.03 release ready. But if you've made bigger changes to the library feel free to close and ignore.

**Comment by agarwal** [comment]
I'll leave it open so we can remember to make the corresponding fix in the new branch. Thanks for reporting it.

**Comment by rleonid** [comment]
Closing as I'll just create a new branch/PR based off of latest changes.

**Comment by agarwal** [comment]
Fixed in 5ea1eb943b0d09175b152dc75031183ab78c3614.

**Pull request closed without merging**
